baseURL: "https://wbarczynski.pl"
title: "Everything is iteration ＆ experiment"
paginate: 5
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: Courses
                  url: courses/
                  weight: 4
                - name: Archive
                  url: archives
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: About me
                  url: about/

    # pl:
    #     languageCode: "pl-PL"
    #     weight: 2
    #     title: "Wszystko jest iteracją ＆ eksperymentem"
    #     taxonomies:
    #       category: PLcategories
    #       tag: PLtags
    #       series: PLseries
    #     menu:
    #         main:
    #             - name: Zajęcia
    #               url: courses/
    #               weight: 4
    #             - name: Archiwum
    #               url: archives
    #               weight: 5
    #             - name: Szukaj
    #               url: search/
    #               weight: 10
    #             - name: Tags
    #               url: tags/
    #               weight: 10
    #             - name: O mnie
    #               url: about/
outputs:
    home:
        - HTML
        - RSS
        - JSON
params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: "WB"
    # author: ["Me", "You"] # multiple authors

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowToc: true
    # comments: false
    images: ["img/cover.jpeg"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true